### PR TITLE
Changed the tick detection to use edcd's site instead

### PR DESCRIPTION
**Pull request by ZenonSeth**
## Description

These changes are to use the EDCD tick API instead of EliteBGS's API when checking for a new tick. There's a few reasons to do this:

## Reasoning

- EliteBGS author, Garud, has noted he has increasingly less time to maintain and extend EliteBGS-related apps, including the tick detector and the bot
- EliteBGS is a great set of tools widely used by the Elite community up to now, but whilst EliteBGS looks for new contributors it's stability and data / analysis capabilities have had more downtime
- Tick detection has been sporadic in places as a result, sometimes missing irregular ticks
- Therefore a move to a more stable & dedicated service hosted by edcd.io seems to provide more stability and accuracy going forward

## Examples

This week alone, at least 2 ticks so far were missed by EliteBGS, and were seemingly not detected even hours after the tick occurred, but are correctly picked up by EDCD:

Example 1, taken on 2023-12-22:
ex_missing_tick

Example 2, taken on 2023-12-23:
ex_missing_tick2

## Testing

The plugin changes were tested by a few commanders, including myself, in the Ace Exploration squadron. The changes work correctly with all functionality related to ticks - the previous list of tick activity, the posting/updating to Discord and of course, the detection of new ticks.

### CODE REVIEW

**Comment by aussig** [comment]
Thank you very much for the contribution.

I have been considering this myself for some time (see #101) but I held off because although elitebgs.app has been missing ticks,  edcd.io has been having the opposite problem - regularly reporting two ticks per day. Not sure which is worse TBH.

Have you been seeing this in your testing?

Another reason I was holding is because a CMDR Zoy on the EDBGS Discord said that he was working on an alternate tick detector and was having some success with it. I've just pinged him to see whether he's made any progress on that.

I do value your contribution though, so will keep your PR open for the moment

**Comment by ZenonSeth** [comment]
I haven't used EDCD as a source for ticks for too long, but I haven't seen many double ticks, and I have been under the impression that those are not in error, but rather they are actually what is happening. I've asked one of my squadron CMDRs who has more experience with EDCD to reply when he gets a chance.

As for what is "worse" - personally missing a tick upsets my reporting of bgs-related activity more than an extra tick does (again if that is even in error - I don't know), which is why using EDCD is preferrable to me and a few people in my squadron. I know manually forcing a tick is an option in the UI, but that's not consistent across commanders and it also can cause a "double tick" type situation to occur if/when the real tick happens at a time after the forced tick.

**Comment by aussig** [comment]
Interesting dilemma. Also, I also had a thought that it might be good to give the user the choice and have a setting in the preferences to switch - using your code and tick ID generation for EDCD, and my code for EliteBGS.  Though the downside of that is it wouldn't be great if users in a particular squadron used different tick detectors!

Let's see what your colleague says, and I'll see what CMDR Zoy has to say about his project too.

**Comment by combivanCoder** [comment]
> Another reason I was holding is because a CMDR Zoy on the EDBGS Discord said that he was working on an alternate tick detector and was having some success with it. I've just pinged him to see whether he's made any progress on that.

Hello! @ZenonSeth pinged me to have a look at this one. Double ticks are definiely a thing, and have been observed in the wild on multiple occasions. From what I've seen tick.edcd.io appears to be much more accurate as I haven't seen additional ticks where one has not been noted in game - got to caveat that with stating that from my perspective only vs. EBGS sometimes skips days entirely.

Would be great if Zoy could link up with the EDCD group to potentially replace the existing [tick detector](https://github.com/EDCD/TickDetector) repo with his new one. That's been relatively solid but doesn't appear to be maintained.

Not sure if you're on the Elite Kode discord but I did ask the EBGS author a couple of questions in November:
https://discord.com/channels/370118111661129728/370118111661129730/1173207108339118151

EBGS basically isn't under any significant development and isn't reliable enough.

> I do value your contribution though, so will keep your PR open for the moment

That makes sense. We're testing @ZenonSeth's fork in-squadron and will relate any issues back to him to review for that fork. EBGS just isn't operational enough for us to make it work right now.

**Comment by aussig** [comment]
Thankyou for the extra info, I did follow up with Zoy and he has [responded with some data in the EDBGS Discord](https://discord.com/channels/483005833853009950/502784093847552001/1188128110424633354) showing his code working - it sounds like he's getting results on the data collection side and now needs to build the statistical analysis layer.  At least a few more weeks off I reckon.

The reason I raised the issue of double ticks with the EDCD detector is I changed our own squadron Discord bot to use the EDCD tick detector around a year ago, and recently we have seen regular double tick reports.  We have observed that these are not 'real' double ticks - i.e. looking at any **individual** system shows only a single INF change. Our suspicion is that the tick is taking a lot longer to sweep across the whole galaxy so it's statistically detecting tick clusters in two separate regions and flagging this as two ticks. 

Let's keep the discussion open.  I'm particularly interested in your experience testing @ZenonSeth's fork over a longer period of time, seeing whether you're seeing regular double ticks

**Comment by combivanCoder** [comment]
> The reason I raised the issue of double ticks with the EDCD detector is I changed our own squadron Discord bot to use it around a year ago, and recently we have seen regular double tick reports. We have observed that these are not 'real' double ticks - i.e. looking at any **individual** system shows only a single INF change. Our suspicion is that the tick is taking a lot longer to sweep across the whole galaxy so it's statistically detecting tick clusters in two separate regions and flagging this as two ticks.

Zoy's work looks very promising. 

We've been extending our test period but are seeing almost daily double ticks. Suspect this is possibly configuration of selected analysis systems used to determine the tick, although could be a code issue. I'm personally leaning towards giving Zoy a few more weeks to produce something more reliable at this stage. @ZenonSeth changes demonstrate how simple it might be to integrate this new service when it's available.

We also noticed a strange edge case we're looking into, might be related to the change in `tick_id` generation.

**Comment by aussig** [comment]
> We've been extending our test period but are seeing almost daily double ticks. Suspect this is possibly configuration of selected analysis systems used to determine the tick, although could be a code issue. I'm personally leaning towards giving Zoy a few more weeks to produce something more reliable at this stage. @ZenonSeth changes demonstrate how simple it might be to integrate this new service when it's available.

Yeah it's definitely generating double ticks most days now, so that's not really ideal for Tally. The interesting thing is that I believe EliteBGS uses the same tick detector, so it must be applying some filtering to cut it down to 1 tick per 24h. Perhaps it's that filtering that is sometimes too draconian and reports no tick at all...

I agree we should see what Zoy produces.

> We also noticed a strange edge case we're looking into, might be related to the change in `tick_id` generation.

Providing the hash you create is compatible with Windows file naming it should be ok (and you're using MD5, which is fine).  FYI I use `token_hex()` from `secrets` to manufacture tick IDs [when I need to](https://github.com/aussig/BGS-Tally/blob/25674751da0cfe06451dc9551ba3c4e2af08b55e/bgstally/tick.py#L57) (i.e. when the user forces a tick).

**Comment by ZenonSeth** [comment]
> Providing the hash you create is compatible with Windows file naming it should be ok (and you're using MD5, which is fine).
Yeah, I had a look, the edge case being mentioned here isn't due to the generated ID. I thought md5 was a good deterministic solution to have a reproducible ID.

**Comment by aussig** [comment]
> Yeah, I had a look, the edge case being mentioned here isn't due to the generated ID. I thought md5 was a good deterministic solution to have a reproducible ID.

Is it only affecting your branch and not something I need to look at in the main code?

> Also if the other tick detector is getting along, feel free to close this PR anytime.

I'm going to leave it open for a little - if Zoy's work comes to nothing I might expand on your work to include a user setting to choose which tick detector to use. I'm overwhelmed with work at the moment so I doubt you'll have to spend much time merging changes from `develop` over the next couple of weeks at least.

**Comment by aussig** [comment]
Closing, as now superseded by the switch to Zoy's tick detector (#239)

**Pull request closed without merging**
